{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-test",
    "version": "4.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.4"
          }
        },
        {
          "group": "net.minidev",
          "module": "json-smart",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.6"
          }
        },
        {
          "group": "org.awaitility",
          "module": "awaitility",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.20.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.20.0"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.10.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-4.0.2.jar",
          "url": "spring-boot-starter-test-4.0.2.jar",
          "size": 2048,
          "sha512": "06a4ed92c869e18ea15144bc4d32f5ad085088f3d3429f33e0ea81cff39825e2abea4ad0e6fade67255e38474f704f4f1730cb3a90f08286c76bc0dd66e3d12c",
          "sha256": "9bb6b1c106bd2648f8b3d8a0bfb8c562299b24e0d7dd06e4c4e5010406d3a494",
          "sha1": "7db044eeb1b61de514df1d129ab56e23cae4c08f",
          "md5": "d648c6077dc644ad0165ec8e6851c849"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.4"
          }
        },
        {
          "group": "net.minidev",
          "module": "json-smart",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.6"
          }
        },
        {
          "group": "org.awaitility",
          "module": "awaitility",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.20.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.20.0"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.10.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-4.0.2.jar",
          "url": "spring-boot-starter-test-4.0.2.jar",
          "size": 2048,
          "sha512": "06a4ed92c869e18ea15144bc4d32f5ad085088f3d3429f33e0ea81cff39825e2abea4ad0e6fade67255e38474f704f4f1730cb3a90f08286c76bc0dd66e3d12c",
          "sha256": "9bb6b1c106bd2648f8b3d8a0bfb8c562299b24e0d7dd06e4c4e5010406d3a494",
          "sha1": "7db044eeb1b61de514df1d129ab56e23cae4c08f",
          "md5": "d648c6077dc644ad0165ec8e6851c849"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-4.0.2-javadoc.jar",
          "url": "spring-boot-starter-test-4.0.2-javadoc.jar",
          "size": 2048,
          "sha512": "06a4ed92c869e18ea15144bc4d32f5ad085088f3d3429f33e0ea81cff39825e2abea4ad0e6fade67255e38474f704f4f1730cb3a90f08286c76bc0dd66e3d12c",
          "sha256": "9bb6b1c106bd2648f8b3d8a0bfb8c562299b24e0d7dd06e4c4e5010406d3a494",
          "sha1": "7db044eeb1b61de514df1d129ab56e23cae4c08f",
          "md5": "d648c6077dc644ad0165ec8e6851c849"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-4.0.2-sources.jar",
          "url": "spring-boot-starter-test-4.0.2-sources.jar",
          "size": 2048,
          "sha512": "06a4ed92c869e18ea15144bc4d32f5ad085088f3d3429f33e0ea81cff39825e2abea4ad0e6fade67255e38474f704f4f1730cb3a90f08286c76bc0dd66e3d12c",
          "sha256": "9bb6b1c106bd2648f8b3d8a0bfb8c562299b24e0d7dd06e4c4e5010406d3a494",
          "sha1": "7db044eeb1b61de514df1d129ab56e23cae4c08f",
          "md5": "d648c6077dc644ad0165ec8e6851c849"
        }
      ]
    }
  ]
}
