{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.jupiter",
    "module": "junit-jupiter-params",
    "version": "6.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "6.0.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-params-6.0.2.jar",
          "url": "junit-jupiter-params-6.0.2.jar",
          "size": 296552,
          "sha512": "b5e44bef00c1863aecd0e8e065ba7ab66f5dd831bc786725e768d54a01287c02d8e776f911281e23fcae5db7f6e9f94d9b1bd102340aa90f1c7bda5bebc071ac",
          "sha256": "4c6f5877e852a7b891207c6e8d6a5eb19680d25b0c401d09a649d1ea17117b59",
          "sha1": "960b882fd207c962066024b251699f2ca269dfac",
          "md5": "7045019751cec27e2a35ca14691ed294"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "6.0.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "6.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-params-6.0.2.jar",
          "url": "junit-jupiter-params-6.0.2.jar",
          "size": 296552,
          "sha512": "b5e44bef00c1863aecd0e8e065ba7ab66f5dd831bc786725e768d54a01287c02d8e776f911281e23fcae5db7f6e9f94d9b1bd102340aa90f1c7bda5bebc071ac",
          "sha256": "4c6f5877e852a7b891207c6e8d6a5eb19680d25b0c401d09a649d1ea17117b59",
          "sha1": "960b882fd207c962066024b251699f2ca269dfac",
          "md5": "7045019751cec27e2a35ca14691ed294"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-params-6.0.2-javadoc.jar",
          "url": "junit-jupiter-params-6.0.2-javadoc.jar",
          "size": 4492850,
          "sha512": "978861f048709c322197e41cce5969e9bf4e1b84e360f6fff9d27962f91dd970dc4113a3fb00cf3334ed056383777403b6eb8b0a2213dbd87046736c673cc709",
          "sha256": "0207103cfa83c262daba3ed7b69e63e6db6a522c53b22e53e59c14c6945be5fb",
          "sha1": "ddf1b3f859a0dd8f7171b0a980cef4d6017f1e44",
          "md5": "b1064dbdf851bae423cb73f5e7c0ec32"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-params-6.0.2-sources.jar",
          "url": "junit-jupiter-params-6.0.2-sources.jar",
          "size": 139532,
          "sha512": "4d8060dcb29cbea64ad17645572313e5489862fcdab77fadc94677aab770bac818bcc0a71b606c1d1f5e34378e107b90257bdf6e7eb5e7fe1de857629f166bb1",
          "sha256": "f0dcf217100b06b98cd36c2e74fb919c74e3024faad868bac9eba6ff00c7c263",
          "sha1": "35ed7e38169e88e750d295b91ae465d18233b829",
          "md5": "037556c021c9a563a9e71e1eacbd6187"
        }
      ]
    }
  ]
}
