{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat-runtime",
    "version": "4.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-tomcat",
          "version": {
            "requires": "4.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-web-server",
          "version": {
            "requires": "4.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "11.0.15"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "11.0.15"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "11.0.15"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.2.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.2.jar",
          "size": 2002,
          "sha512": "41ad2328e474ca572fa97e1a44e2253d3af8c7a4896cc01b6e8dadd9743da879f910ec90e1cfabe36f647b8a4a69d01e3752fb529bebfa55081e17caf22ff5b6",
          "sha256": "e338437f818f38b611a9c6d87bed067f3771967522b1d7bbb6cc53cf2164c04b",
          "sha1": "1721a88cfff65f7589b8078fa83722da787112a0",
          "md5": "e5f09e2277beb6b234f8d584688b24c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-tomcat",
          "version": {
            "requires": "4.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-web-server",
          "version": {
            "requires": "4.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "11.0.15"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "11.0.15"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "11.0.15"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.2.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.2.jar",
          "size": 2002,
          "sha512": "41ad2328e474ca572fa97e1a44e2253d3af8c7a4896cc01b6e8dadd9743da879f910ec90e1cfabe36f647b8a4a69d01e3752fb529bebfa55081e17caf22ff5b6",
          "sha256": "e338437f818f38b611a9c6d87bed067f3771967522b1d7bbb6cc53cf2164c04b",
          "sha1": "1721a88cfff65f7589b8078fa83722da787112a0",
          "md5": "e5f09e2277beb6b234f8d584688b24c8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.2-javadoc.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.2-javadoc.jar",
          "size": 2002,
          "sha512": "41ad2328e474ca572fa97e1a44e2253d3af8c7a4896cc01b6e8dadd9743da879f910ec90e1cfabe36f647b8a4a69d01e3752fb529bebfa55081e17caf22ff5b6",
          "sha256": "e338437f818f38b611a9c6d87bed067f3771967522b1d7bbb6cc53cf2164c04b",
          "sha1": "1721a88cfff65f7589b8078fa83722da787112a0",
          "md5": "e5f09e2277beb6b234f8d584688b24c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.2-sources.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.2-sources.jar",
          "size": 2002,
          "sha512": "41ad2328e474ca572fa97e1a44e2253d3af8c7a4896cc01b6e8dadd9743da879f910ec90e1cfabe36f647b8a4a69d01e3752fb529bebfa55081e17caf22ff5b6",
          "sha256": "e338437f818f38b611a9c6d87bed067f3771967522b1d7bbb6cc53cf2164c04b",
          "sha1": "1721a88cfff65f7589b8078fa83722da787112a0",
          "md5": "e5f09e2277beb6b234f8d584688b24c8"
        }
      ]
    }
  ]
}
