{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webmvc",
    "version": "7.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-7.0.3.jar",
          "url": "spring-webmvc-7.0.3.jar",
          "size": 1104184,
          "sha512": "5562139105916613a5a131f4d07a31f0dc299bb813807686aec37601e5c0333b8e7c300ac3ebbbbcd495bf2b52ec4c1f0a2ba36e3d15b0bffe66bfa1a9354780",
          "sha256": "52e6f0a2d96d30f591d78eca1e94d33c1e510eeab2c7063a25d126970f76e4e5",
          "sha1": "8ceb3c7d21b317e87be72c0ba61fcab46b992b29",
          "md5": "06966aab587a2a2b4aa77701f3ff2e38"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-7.0.3.jar",
          "url": "spring-webmvc-7.0.3.jar",
          "size": 1104184,
          "sha512": "5562139105916613a5a131f4d07a31f0dc299bb813807686aec37601e5c0333b8e7c300ac3ebbbbcd495bf2b52ec4c1f0a2ba36e3d15b0bffe66bfa1a9354780",
          "sha256": "52e6f0a2d96d30f591d78eca1e94d33c1e510eeab2c7063a25d126970f76e4e5",
          "sha1": "8ceb3c7d21b317e87be72c0ba61fcab46b992b29",
          "md5": "06966aab587a2a2b4aa77701f3ff2e38"
        }
      ]
    }
  ]
}
