{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "4.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-4.0.2.jar",
          "url": "spring-boot-starter-4.0.2.jar",
          "size": 2025,
          "sha512": "29c8a796db5906d415658b09eab1c1e9ed43a4212a86384cb7778d72a2e9c1749bbb750ffa6e2151878b2f05a8a30c6e77b2c5e7cc588cb097d54743bbea0eba",
          "sha256": "f832dee2a56a2a7fce8590b1cf10c9bf311a697359565a99bc831dc754bfead7",
          "sha1": "d31987d4c1f6af48db2a53605829780365354e85",
          "md5": "d67f4f557307f712fffa514078db2f52"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-4.0.2.jar",
          "url": "spring-boot-starter-4.0.2.jar",
          "size": 2025,
          "sha512": "29c8a796db5906d415658b09eab1c1e9ed43a4212a86384cb7778d72a2e9c1749bbb750ffa6e2151878b2f05a8a30c6e77b2c5e7cc588cb097d54743bbea0eba",
          "sha256": "f832dee2a56a2a7fce8590b1cf10c9bf311a697359565a99bc831dc754bfead7",
          "sha1": "d31987d4c1f6af48db2a53605829780365354e85",
          "md5": "d67f4f557307f712fffa514078db2f52"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-4.0.2-javadoc.jar",
          "url": "spring-boot-starter-4.0.2-javadoc.jar",
          "size": 2025,
          "sha512": "29c8a796db5906d415658b09eab1c1e9ed43a4212a86384cb7778d72a2e9c1749bbb750ffa6e2151878b2f05a8a30c6e77b2c5e7cc588cb097d54743bbea0eba",
          "sha256": "f832dee2a56a2a7fce8590b1cf10c9bf311a697359565a99bc831dc754bfead7",
          "sha1": "d31987d4c1f6af48db2a53605829780365354e85",
          "md5": "d67f4f557307f712fffa514078db2f52"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-4.0.2-sources.jar",
          "url": "spring-boot-starter-4.0.2-sources.jar",
          "size": 2025,
          "sha512": "29c8a796db5906d415658b09eab1c1e9ed43a4212a86384cb7778d72a2e9c1749bbb750ffa6e2151878b2f05a8a30c6e77b2c5e7cc588cb097d54743bbea0eba",
          "sha256": "f832dee2a56a2a7fce8590b1cf10c9bf311a697359565a99bc831dc754bfead7",
          "sha1": "d31987d4c1f6af48db2a53605829780365354e85",
          "md5": "d67f4f557307f712fffa514078db2f52"
        }
      ]
    }
  ]
}
