{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-jackson",
    "version": "4.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-jackson",
          "version": {
            "requires": "4.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jackson-4.0.2.jar",
          "url": "spring-boot-starter-jackson-4.0.2.jar",
          "size": 1998,
          "sha512": "7c47659a86830861d07f65d809607143fb3133fe8d6e6c9ab03e8b03491146051799bbecf68d5873c151b25f2dcb5f195126addd8be2b9b98992dad0c954d5e3",
          "sha256": "8a933fd52e248c30788f2b5593c616158290761fa7dcb4d82dcd235e1f3c1d41",
          "sha1": "9e75c7cb0b8ea189acb51cd2d2f25a165746b82b",
          "md5": "55d6e7676f6c98c8502dd9b0926296bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-jackson",
          "version": {
            "requires": "4.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jackson-4.0.2.jar",
          "url": "spring-boot-starter-jackson-4.0.2.jar",
          "size": 1998,
          "sha512": "7c47659a86830861d07f65d809607143fb3133fe8d6e6c9ab03e8b03491146051799bbecf68d5873c151b25f2dcb5f195126addd8be2b9b98992dad0c954d5e3",
          "sha256": "8a933fd52e248c30788f2b5593c616158290761fa7dcb4d82dcd235e1f3c1d41",
          "sha1": "9e75c7cb0b8ea189acb51cd2d2f25a165746b82b",
          "md5": "55d6e7676f6c98c8502dd9b0926296bc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jackson-4.0.2-javadoc.jar",
          "url": "spring-boot-starter-jackson-4.0.2-javadoc.jar",
          "size": 1998,
          "sha512": "7c47659a86830861d07f65d809607143fb3133fe8d6e6c9ab03e8b03491146051799bbecf68d5873c151b25f2dcb5f195126addd8be2b9b98992dad0c954d5e3",
          "sha256": "8a933fd52e248c30788f2b5593c616158290761fa7dcb4d82dcd235e1f3c1d41",
          "sha1": "9e75c7cb0b8ea189acb51cd2d2f25a165746b82b",
          "md5": "55d6e7676f6c98c8502dd9b0926296bc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jackson-4.0.2-sources.jar",
          "url": "spring-boot-starter-jackson-4.0.2-sources.jar",
          "size": 1998,
          "sha512": "7c47659a86830861d07f65d809607143fb3133fe8d6e6c9ab03e8b03491146051799bbecf68d5873c151b25f2dcb5f195126addd8be2b9b98992dad0c954d5e3",
          "sha256": "8a933fd52e248c30788f2b5593c616158290761fa7dcb4d82dcd235e1f3c1d41",
          "sha1": "9e75c7cb0b8ea189acb51cd2d2f25a165746b82b",
          "md5": "55d6e7676f6c98c8502dd9b0926296bc"
        }
      ]
    }
  ]
}
